
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Age = 28F,
    Gender = @"Female",
    TotalPageViews = 32F,
    TimeOnSite = 18.2F,
    PreviousPurchases = 5F,
    FavoriteCategory = @"NonFiction",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual WillBuy with predicted WillBuy from sample data...\n\n");


Console.WriteLine($"Age: {28F}");
Console.WriteLine($"Gender: {@"Female"}");
Console.WriteLine($"TotalPageViews: {32F}");
Console.WriteLine($"TimeOnSite: {18.2F}");
Console.WriteLine($"PreviousPurchases: {5F}");
Console.WriteLine($"FavoriteCategory: {@"NonFiction"}");
Console.WriteLine($"WillBuy: {0F}");


var sortedScoresWithLabel = MLModel1.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

